# Generated by Django 3.1 on 2020-09-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
